#include <symath/symbols.h>

using namespace symath;

symbol symbols::a(L'a',"a");
symbol symbols::b(L'b',"b");
symbol symbols::c(L'c',"c");
symbol symbols::d(L'd',"d");
symbol symbols::e(L'e',"e");
symbol symbols::f(L'f',"f");
symbol symbols::g(L'g',"g");
symbol symbols::h(L'h',"h");
symbol symbols::i(L'i',"i");
symbol symbols::j(L'j',"j");
symbol symbols::k(L'k',"k");
symbol symbols::l(L'l',"l");
symbol symbols::m(L'm',"m");
symbol symbols::n(L'n',"n");
symbol symbols::o(L'o',"o");
symbol symbols::p(L'p',"p");
symbol symbols::q(L'q',"q");
symbol symbols::r(L'r',"r");
symbol symbols::s(L's',"s");
symbol symbols::t(L't',"t");
symbol symbols::u(L'u',"u");
symbol symbols::v(L'v',"v");
symbol symbols::w(L'w',"w");
symbol symbols::x(L'x',"x");
symbol symbols::y(L'y',"y");
symbol symbols::z(L'z',"z");

symbol symbols::A(L'A',"A");
symbol symbols::B(L'B',"B");
symbol symbols::C(L'C',"C");
symbol symbols::D(L'D',"D");
symbol symbols::E(L'E',"E");
symbol symbols::F(L'F',"F");
symbol symbols::G(L'G',"G");
symbol symbols::H(L'H',"H");
symbol symbols::I(L'I',"I");
symbol symbols::J(L'J',"J");
symbol symbols::K(L'K',"K");
symbol symbols::L(L'L',"L");
symbol symbols::M(L'M',"M");
symbol symbols::N(L'N',"N");
symbol symbols::O(L'O',"O");
symbol symbols::P(L'P',"P");
symbol symbols::Q(L'Q',"Q");
symbol symbols::R(L'R',"R");
symbol symbols::S(L'S',"S");
symbol symbols::T(L'T',"T");
symbol symbols::U(L'U',"U");
symbol symbols::V(L'V',"V");
symbol symbols::W(L'W',"W");
symbol symbols::X(L'X',"X");
symbol symbols::Y(L'Y',"Y");
symbol symbols::Z(L'Z',"Z");

symbol symbols::alpha     (0x03B1,"\\alpha");
symbol symbols::beta      (0x03B2,"\\beta");
symbol symbols::gamma     (0x03B3,"\\gamma");
symbol symbols::delta     (0x03B4,"\\delta");
symbol symbols::epsilon   (0x03F5,"\\epsilon");
symbol symbols::varepsilon(0x03B5,"\\varepsilon");
symbol symbols::zeta      (0x03B6,"\\zeta");
symbol symbols::eta       (0x03B7,"\\eta");
symbol symbols::theta     (0x03B8,"\\theta");
symbol symbols::vartheta  (0x03D1,"\\vartheta");
symbol symbols::iota      (0x03B9,"\\iota");
symbol symbols::kappa     (0x03BA,"\\kappa");
symbol symbols::lambda    (0x03BB,"\\lambda");
symbol symbols::mu        (0x03BC,"\\mu");
symbol symbols::nu        (0x03BD,"\\nu");
symbol symbols::xi        (0x03BE,"\\xi");
symbol symbols::pi        (0x03C0,"\\pi");
symbol symbols::varpi     (0x03D6,"\\varpi");
symbol symbols::rho       (0x03C1,"\\rho");
symbol symbols::varrho    (0x03F1,"\\varrho");
symbol symbols::sigma     (0x03C3,"\\sigma");
symbol symbols::varsigma  (0x03C2,"\\varsigma");
symbol symbols::tau       (0x03C4,"\\tau");
symbol symbols::upsilon   (0x03C5,"\\upsilon");
symbol symbols::phi       (0x03D5,"\\phi");
symbol symbols::varphi    (0x03C6,"\\varphi");
symbol symbols::chi       (0x03C7,"\\chi");
symbol symbols::psi       (0x03C8,"\\psi");
symbol symbols::omega     (0x03C9,"\\omega");

symbol symbols::Gamma     (0x0393,"\\Gamma");
symbol symbols::Delta     (0x0394,"\\Delta");
symbol symbols::Theta     (0x0398,"\\Theta");
symbol symbols::Lambda    (0x039B,"\\Lambda");
symbol symbols::Xi        (0x039E,"\\Xi");
symbol symbols::Pi        (0x03A0,"\\Pi");
symbol symbols::Sigma     (0x03A3,"\\Sigma");
symbol symbols::Upsilon   (0x03A5,"\\Upsilon");
symbol symbols::Phi       (0x03A6,"\\Phi");
symbol symbols::Psi       (0x03A8,"\\Psi");
symbol symbols::Omega     (0x03A9,"\\Omega");

